### ISSUE TITLE
Ссылка на демо

### ISSUE THREAD

**Issue by VadimCpp** [askomarov/bicycle#1]
Есть ссылка, где можно посмотреть как работает проект? (чтобы не скачивать исходники)

**Comment by askomarov** [comment]
Здраствуйте, расскажите про Вашу цель, помогаете сделать мне лучше?)  Добавил ссылку в описание репозитория.

**Comment by VadimCpp** [comment]
Спасибо большое. 
Мне понравилось Ваше резюме и я заглянул в гитхаб. 
Немного улучшили.
